fix a minor issue of rosa provision

diff --git a/common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml b/common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml
--- a/common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml
+++ b/common/tasks/rosa/hosted-cp/rosa-hcp-provision/rosa-hcp-provision.yaml
@@ -117,6 +117,11 @@ spec:
             fi
         }
 
+        # Function to check if the API server is ready
+        check_api_server() {
+          kubectl get nodes >/dev/null 2>/dev/null || true
+        }
+
         deploy_cluster() {
             printf "INFO: Log in to your Red Hat account...\n" 
             config_aws_creds
@@ -169,9 +174,22 @@ spec:
 
             #Workaround: Check if apiserver is ready by calling kubectl get nodes
             printf "INFO: Check if apiserver is ready...\n"
-            if ! timeout 300s bash -c "while ! kubectl get nodes >/dev/null 2>/dev/null; do printf '.'; sleep 10; done"; then
-                echo "ERROR: API server is not ready" >&2
-                exit 1
+            # Timeout loop to wait for the API server to be ready
+            timeout 300s bash -c '
+            while true; do
+              if check_api_server; then
+                echo "API server is ready"
+                exit 0
+              else
+                echo -n "."  # Print a dot to indicate progress
+                sleep 10
+              fi
+            done
+            '
+
+            if [ $? -ne 0 ]; then
+              echo "ERROR: API server is not ready" >&2
+              exit 1
             fi
             check_clusteroperators
         }
